# Generated by Django 2.2.6 on 2019-10-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
